export enum MNML_STATE {
    MIDI_UNAVAILABLE,
    MIDI_NOT_ENABLED,
    NO_OUTPUT_AVAILABLE,
    NO_OUTPUT_SELECTED,
    READY,
    PLAYING,
    PAUSED,
    UNKNOWN,
}

// type EnumValue<Enum> = Enum[keyof Enum]
//
// export const MNML_STATE_ENUM: {
//     [key in keyof typeof MNML_STATE]: MNML_STATE[key]
// } = {
//     MIDI_UNAVAILABLE: MNML_STATE.MIDI_UNAVAILABLE,
//     MIDI_NOT_ENABLED]: MNML_STATE.MIDI_NOT_ENABLED,
//     NO_OUTPUT_AVAILABLE]: MNML_STATE.NO_OUTPUT_AVAILABLE,
//     NO_OUTPUT_SELECTED]: MNML_STATE.NO_OUTPUT_SELECTED,
//     READY]: MNML_STATE.READY,
//     PLAYING: MNML_STATE.PLAYING,
//     PAUSED: MNML_STATE.PAUSED,
//     UNKNOWN: MNML_STATE.UNKNOWN,
// }
