export const GM_PROGRAMS = [
    {
        label: 'Piano',
        items: [
            {program: 1, name: 'Acoustic Grand Piano or Piano 1'},
            {program: 2, name: 'Bright Acoustic Piano or Piano 2'},
            {program: 3, name: 'Electric Grand Piano or Piano 3'},
            {program: 4, name: 'Honky-tonk Piano'},
            {program: 5, name: 'Electric Piano 1'},
            {program: 6, name: 'Electric Piano 2'},
            {program: 7, name: 'Harpsichord'},
            {program: 8, name: 'Clavinet'},
        ],
    },
    {
        label: 'Chromatic Percussion',
        items: [
            {program: 9, name: 'Celesta'},
            {program: 10, name: 'Glockenspiel'},
            {program: 11, name: 'Music Box'},
            {program: 12, name: 'Vibraphone'},
            {program: 13, name: 'Marimba'},
            {program: 14, name: 'Xylophone'},
            {program: 15, name: 'Tubular Bells'},
            {program: 16, name: 'Dulcimer or Santoor'},
        ],
    },
    {
        label: 'Organ',
        items: [
            {program: 17, name: 'Drawbar Organ or Organ 1'},
            {program: 18, name: 'Percussive Organ or Organ 2'},
            {program: 19, name: 'Rock Organ or Organ 3'},
            {program: 20, name: 'Church Organ'},
            {program: 21, name: 'Reed Organ'},
            {program: 22, name: 'Accordion'},
            {program: 23, name: 'Harmonica'},
            {program: 24, name: 'Bandoneon or Tango Accordion'},
        ],
    },
    {
        label: 'Guitar',
        items: [
            {program: 25, name: 'Acoustic Guitar (nylon)'},
            {program: 26, name: 'Acoustic Guitar (steel)'},
            {program: 27, name: 'Electric Guitar (jazz)'},
            {program: 28, name: 'Electric Guitar (clean'},
            {program: 29, name: 'Electric Guitar (muted)'},
            {program: 30, name: 'Electric Guitar (overdrive)'},
            {program: 31, name: 'Electric Guitar (distortion)'},
            {program: 32, name: 'Electric Guitar (harmonics)'},
        ],
    },
    {
        label: 'Bass',
        items: [
            {program: 33, name: 'Acoustic Bass'},
            {program: 34, name: 'Electric Bass (finger)'},
            {program: 35, name: 'Electric Bass (picked)'},
            {program: 36, name: 'Electric Bass (fretless)'},
            {program: 37, name: 'Slap Bass 1'},
            {program: 38, name: 'Slap Bass 2'},
            {program: 39, name: 'Synth Bass 1'},
            {program: 40, name: 'Synth Bass 2'},
        ],
    },
    {
        label: 'Strings',
        items: [
            {program: 41, name: 'Violin'},
            {program: 42, name: 'Viola'},
            {program: 43, name: 'Cello'},
            {program: 44, name: 'Contrabass'},
            {program: 45, name: 'Tremolo Strings'},
            {program: 46, name: 'Pizzicato Strings'},
            {program: 47, name: 'Orchestral Harp'},
            {program: 48, name: 'Timpani'},
        ],
    },
    {
        label: 'Ensemble',
        items: [
            {program: 49, name: 'String Ensemble 1 (often in marcato)'},
            {program: 50, name: 'String Ensemble 2 (slower attack than String Ensemble 1)'},
            {program: 51, name: 'Synth Strings 1'},
            {program: 52, name: 'Synth Strings 2'},
            {program: 53, name: 'Choir Aahs'},
            {program: 54, name: 'Voice Oohs (or Doos)'},
            {program: 55, name: 'Synth Voice or Synth Choir'},
            {program: 56, name: 'Orchestra Hit'},
        ],
    },
    {
        label: 'Brass',
        items: [
            {program: 57, name: 'Trumpet'},
            {program: 58, name: 'Trombone'},
            {program: 59, name: 'Tuba'},
            {program: 60, name: 'Muted Trumpet'},
            {program: 61, name: 'French Horn'},
            {program: 62, name: 'Brass Section'},
            {program: 63, name: 'Synth Brass 1'},
            {program: 64, name: 'Synth Brass 2'},
        ],
    },
    {
        label: 'Reed',
        items: [
            {program: 65, name: 'Soprano Sax'},
            {program: 66, name: 'Alto Sax'},
            {program: 67, name: 'Tenor Sax'},
            {program: 68, name: 'Baritone Sax'},
            {program: 69, name: 'Oboe'},
            {program: 70, name: 'English Horn'},
            {program: 71, name: 'Bassoon'},
            {program: 72, name: 'Clarinet'},
        ],
    },
    {
        label: 'Pipe',
        items: [
            {program: 73, name: 'Piccolo'},
            {program: 74, name: 'Flute'},
            {program: 75, name: 'Recorder'},
            {program: 76, name: 'Pan Flute'},
            {program: 77, name: 'Blown bottle'},
            {program: 78, name: 'Shakuhachi'},
            {program: 79, name: 'Whistle'},
            {program: 80, name: 'Ocarina'},
        ],
    },
    {
        label: 'Synth Lead',
        items: [
            {program: 81, name: 'Lead 1 (square)'},
            {program: 82, name: 'Lead 2 (sawtooth or saw)'},
            {program: 83, name: 'Lead 3 (calliope)'},
            {program: 84, name: 'Lead 4 (chiff)'},
            {program: 85, name: 'Lead 5 (charang)'},
            {program: 86, name: 'Lead 6 (voice)'},
            {program: 87, name: 'Lead 7 (fifths)'},
            {program: 88, name: 'Lead 8 (bass and lead or solo lead)'},
        ],
    },
    {
        label: 'Synth Pad',
        items: [
            {program: 89, name: 'Pad 1 (new age)'},
            {program: 90, name: 'Pad 2 (warm)'},
            {program: 91, name: 'Pad 3 (polysynth or poly)'},
            {program: 92, name: 'Pad 4 (choir)'},
            {program: 93, name: 'Pad 5 (bowed glass or bowed)'},
            {program: 94, name: 'Pad 6 (metallic)'},
            {program: 95, name: 'Pad 7 (halo)'},
            {program: 96, name: 'Pad 8 (sweep)'},
        ],
    },
    {
        label: 'Synth Effects',
        items: [
            {program: 97, name: 'FX 1 (rain)'},
            {program: 98, name: 'FX 2 (soundtrack)'},
            {program: 99, name: 'FX 3 (crystal)'},
            {program: 100, name: 'FX 4 (atmosphere)'},
            {program: 101, name: 'FX 5 (brightness)'},
            {program: 102, name: 'FX 6 (goblins)'},
            {program: 103, name: 'FX 7 (echoes or echo drops)'},
            {program: 104, name: 'FX 8 (sci-fi or star theme)'},
        ],
    },
    {
        label: 'Ethnic',
        items: [
            {program: 105, name: 'Sitar'},
            {program: 106, name: 'Banjo'},
            {program: 107, name: 'Shamisen'},
            {program: 108, name: 'Koto'},
            {program: 109, name: 'Kalimba'},
            {program: 110, name: 'Bag pipe'},
            {program: 111, name: 'Fiddle'},
            {program: 112, name: 'Shanai'},
        ],
    },
    {
        label: 'Percussive',
        items: [
            {program: 113, name: 'Tinkle Bell'},
            {program: 114, name: 'Agog or cowbell'},
            {program: 115, name: 'Steel Drums'},
            {program: 116, name: 'Woodblock'},
            {program: 117, name: 'Taiko Drum or Surdo'},
            {program: 118, name: 'Melodic Tom'},
            {program: 119, name: 'Synth Drum'},
            {program: 120, name: 'Reverse Cymbal'},
        ],
    },
    {
        label: 'Sound Effects',
        items: [
            {program: 121, name: 'Guitar Fret Noise'},
            {program: 122, name: 'Breath Noise'},
            {program: 123, name: 'Seashore'},
            {program: 124, name: 'Bird Tweet'},
            {program: 125, name: 'Telephone Ring'},
            {program: 126, name: 'Helicopter'},
            {program: 127, name: 'Applause'},
            {program: 128, name: 'Gunshot'},
        ],
    },
] as const satisfies Array<{
    label: string
    items: Array<{program: number; name: string}>
}>

export enum GENERAL_MIDI_CC {
    ModulationWheel = 1,
    ChannelVolume = 7,
    ChannelPan = 10,
    ExpressionController = 11,
    SustainPedal = 64,
    SostenutoPedal = 66,
    SoftPedal = 67,
    ResetAllControllers = 121,
    AllNotesOff = 123,
}
